#!/usr/bin/env bash
echo "adding repo and installing neovim"
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim
echo "adding python dependencies for plugvim and nvim"
sudo apt-get install python-dev python-pip python3-dev python3-setuptools
#move and create ~/.local/share/nvim/site/autoload to add plug.vim
cd
cd .local/share
mkdir -p nvim/site/autoload
cd nvim/site/autoload
#retrieves plug.vim instead of cloning whole git
wget https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#creates init.vim director since ubuntu does not have $XDG.CONFIG_HOME defined
#so it doesn't create a default init.vim on install
cd
cd .config
mkdir nvim
echo "remmber to add init.vim to ~/.config/nvim"
