---
# These variables are used from all roles
build_user: "{{ env_build_user }}"
toolchain_dir: /opt/toolchains
arm_toolchain_name: gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
arm_toolchain_url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2

# Gitlab-runner vars
gitlab_runner_package_name: gitlab-runner
gitlab_runner_executable: "{{ gitlab_runner_package_name }}"
gitlab_runner_config_file: "/etc/gitlab-runner/config.toml"
gitlab_runner_coordinator_url: https://gitlab.com
gitlab_runner_token: "{{ env_gitlab_runner_token }}"
gitlab_runner_name: "runner-{{ ansible_date_time.iso8601_basic_short }}"
gitlab_runner_concurrent: 1
