---
- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes

- name: Update apt
  become: true
  apt:
    name: "*"
    state: latest

- name: Install basic tools
  become: true
  apt:
    name: [
    'gawk',
    'wget',
    'git-core',
    'python3',
    'python3-pip',
    'build-essential',
    'cmake',
    'libusb-1.0-0-dev',
    'rsync',
    'locales',
    'pkg-config',
    'udev',
    'automake',
    'autoconf',
    'libtool'
    ]
    state: present

- name: Update python3-pip
  become: true
  command: "python3 -m pip install --upgrade pip"

- name: Ensure UTF-8 local exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: set default locale
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: export LC_ALL="en_US.UTF-8"
    create: yes

- name: Add build user
  become: true
  user:
    name: "{{ build_user }}"
    comment: STM32 Builder
    shell: /bin/bash
    groups: sudo
    append: yes
